block: zram: add MEMCG dependency for LRU_WRITEBACK
The lru writeback code requires memcg support, which is disabled when we use SLMK.

../drivers/block/zram/zram_drv.c:3150:14: error: no member named 'mem_cgroup' in 'struct page'
 3150 |                 if (!page->mem_cgroup ||
      |                      ~~~~  ^
../drivers/block/zram/zram_drv.c:3151:13: error: no member named 'mem_cgroup' in 'struct page'
 3151 |                     page->mem_cgroup->swappiness != NON_LRU_SWAPPINESS) {
      |                     ~~~~  ^
2 errors generated.

Signed-off-by: Flopster101 <nahuelgomez329@gmail.com>