soc: devfreq/exynos-devfreq: Fix uninitialized variable warning
After the update to clang 22 (r584948), the following error appears:

../drivers/devfreq/exynos/exynos-devfreq.c:1975:48: error: variable 'buf' is uninitialized when used here [-Werror,-Wuninitialized]
 1975 |                         of_property_match_string(np, "clock-names", buf))
      |                                                                     ^~~
../drivers/devfreq/exynos/exynos-devfreq.c:1855:17: note: initialize the variable 'buf' to silence this warning
 1855 |         const char *buf;
      |                        ^
      |                         = NULL
1 error generated.

Signed-off-by: Flopster101 <nahuelgomez329@gmail.com>