ASoC: Fix build error in twl4030.c
Fix the (likely cut-n-paste) error by commit
09dc46661098d9f7e82fc1e9db210d248fecb42e, which causes the error below:
  sound/soc/codecs/twl4030.c: In function 'twl4030_read_reg_cache':
  sound/soc/codecs/twl4030.c:152: error: 'cache' undeclared (first use in this function)

Signed-off-by: Takashi Iwai <tiwai@suse.de>