arm64: Fix CONFIG_64BIT leak to userspace
Commit e9db5b71bca4dae5e9fef80c9e087eb65d8babb2 disabled the use of config
options in uapi headers. Use __aarch64__ which is a compiler-defined
method of obtaining the architecture instead of CONFIG_64BIT.

Fixes the following error:
    error: kernel/google/raviole/arch/arm64/include/uapi/asm/sigcontext.h:
        leak CONFIG_64BIT to user-space

Change-Id: Ie1f22679882acbc3e253316d5281287956a4febd