blackfin: twi: Remove bogus #endif
arch/blackfin/mach-bf538/boards/ezkit.c:768:2: error: #endif without #if

Introduced by commit be22a348386538a6afdca1fb7fb02877e26c79cb ("blackfin:
twi: Move TWI peripheral pin request array to platform data"), which
removed the #if, but forgot about the #endif.

Signed-off-by: Geert Uytterhoeven <geert@linux-m68k.org>
Signed-off-by: Steven Miao <realmz6@gmail.com>