input: nt36523_spi: Fix implicit enum conversion error
Some behavior changed in the latest AOSP Clang toolchain (r574158) that
causes this error to pop up.

../drivers/input/touchscreen/novatek/nt36523_spi/nt36xxx.c:2588:11: error: implicit conversion from enumeration type 'enum sec_ts_error' to different enumeration type 'irqreturn_t' (aka 'enum irqreturn') [-Werror,-Wimplicit-enum-enum-cast]
 2588 |                         return SEC_ERROR;
      |                         ~~~~~~ ^~~~~~~~~
1 error generated.

Simply cast it and should be good enough.

Signed-off-by: Flopster101 <nahuelgomez329@gmail.com>