[ARM] 4530/1: MXC: fix elf_hwcap compile breakage as in iop13xx
MXC needs the same change as IOP.  See [ARM] 4494/1
or commit d111901fdf2e206b471af991bf146283c0faa985

An undefined reference to elf_hwcap prevents linkage, due
to changes made by a72a016ae2576d4e73409fabef7cbdd2f30e82ef
and 7a9eee2337a82ef37c925b2e064a67eecfe01249

Removing processor.h removes the extern definition of
elf_hwcap, which fixes the link issue, but forgets cpu_relax().
So, instead, we'll call barrier() directly.

Cc: Lennert Buytenhek <kernel@wantstofly.org>
Cc: Catalin Marinas <catalin.marinas@arm.com>
Acked-by: Ross Wille <wille@freescale.com>
Signed-off-by: Quinn Jensen <quinn.jensen@freescale.com>
Signed-off-by: Russell King <rmk+kernel@arm.linux.org.uk>