Revert "[SCSI] cnic: fix error: implicit declaration of function ‘__symbol_get’"
This reverts commit f7df276d0ea6acf5516503e5d256d0692ed69b67.

All the commit did was add a second #include of <linux/module.h> which is
the wrong fix.

Signed-off-by: James Bottomley <James.Bottomley@HansenPartnership.com>