ARM: mxs: fix compile error caused by prom_update_property change
The commit d9055a8 (of: Improve prom_update_property() function)
changed prom_update_property interface, and causes the compile
error below.

  CC      arch/arm/mach-mxs/mach-mxs.o
arch/arm/mach-mxs/mach-mxs.c: In function ‘update_fec_mac_prop’:
arch/arm/mach-mxs/mach-mxs.c:216:4: error: too many arguments to function ‘prom_update_property’
include/linux/of.h:263:12: note: declared here

Update the caller update_fec_mac_prop to fix the error.

Signed-off-by: Shawn Guo <shawn.guo@linaro.org>
Signed-off-by: Olof Johansson <olof@lixom.net>