tracing, net: fix net tree and tracing tree merge interaction
Today's linux-next build (powerpc ppc64_defconfig) failed like this:

 In file included from net/core/skbuff.c:69:
 include/trace/skb.h:4: error: expected ')' before '(' token
 include/trace/skb.h:4: error: expected ')' before '(' token
 [...]

Caused by commit b684a69f163da47950548b1593ef358683323244 ("tracing:
replace TP<var> with TP_<var>") from the tracing tree interacting with
commit aee949446a963f0c8d66474e782d47a231cb34df ("Network Drop Monitor:
Add trace declaration for skb frees") from the net tree.

Acked-by: David S. Miller <davem@davemloft.net>
Signed-off-by: Ingo Molnar <mingo@elte.hu>