[ARM] 4494/1: iop13xx: fix up elf_hwcap compile breakage
arch/arm/boot/compressed/misc.o: In function `valid_user_regs':
misc.c:(.text+0x74): undefined reference to `elf_hwcap'

This triggers after the various elf_hwcap cleanups in:
a72a016ae2576d4e73409fabef7cbdd2f30e82ef
7a9eee2337a82ef37c925b2e064a67eecfe01249

include/asm-arm/arch-iop13xx/uncompress.h calls cpu_relax while spinning on
a register value.  cpu_relax requires processor.h->ptrace.h->hwcap.h

'elf_hwcap' is defined as an extern, but since the uncompressor does not
link against arch/arm/kernel/setup.c 'elf_hwcap' remains undefined.

Fix is to open code the cpu_relax() call as barrier().

Cc: Lennert Buytenhek <kernel@wantstofly.org>
Cc: Catalin Marinas <catalin.marinas@arm.com>
Signed-off-by: Dan Williams <dan.j.williams@intel.com>
Signed-off-by: Russell King <rmk+kernel@arm.linux.org.uk>