input: nt36523_spi: add missing prototype in function declaration
../drivers/input/touchscreen/novatek/nt36523_spi/nt36xxx.c:3608:28: error: a function declaration without a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
 3608 | bool nvt_ts_lcd_power_check()
      |                            ^
      |                             void
1 error generated.

Signed-off-by: Nahuel Gómez <nahuelgomez329@gmail.com>