Revert "net: dccp: initialize (addr,port) listening hashtable"
This reverts commit 056a5ef368039e212ba8458cf460d47082b2521e.

Cause build failures when DCCP is modular.

ERROR: "inet_hashinfo2_init" [net/dccp/dccp.ko] undefined!

Signed-off-by: David S. Miller <davem@davemloft.net>