fs: proc: fix SUS_MAP unused variable warnings
../fs/proc/base.c:2491:16: error: unused variable 'inode' [-Werror,-Wunused-variable]
 2491 |         struct inode *inode;
      |                       ^~~~~
1 error generated.
../fs/proc/task_mmu.c:1998:25: error: unused variable 'vma' [-Werror,-Wunused-variable]
 1998 |         struct vm_area_struct *vma;
      |                                ^~~
1 error generated.

Signed-off-by: Flopster101 <nahuelgomez329@gmail.com>