Revert "usb: host/sl811-hcd: fix sparse warning"
This reverts commit 17eb26c39cd72713331cce8a9bccee05e003c7c8.

Commit 17eb26c39cd7 results in the following error when compiling
x86_64:allyesconfig.

sl811_cs.c:(.text+0x1d3cb72): undefined reference to `sl811h_driver'

Fixes: 17eb26c39cd7 ("usb: host/sl811-hcd: fix sparse warning")
Cc: Lad, Prabhakar <prabhakar.csengg@gmail.com>
Signed-off-by: Guenter Roeck <linux@roeck-us.net>
Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>