tty/amiserial: Add missing argument for tty_unlock()
commit 9d8c829b0a2544e7c586481e2c8265a7d821d029 ("tty_lock: Localise the lock")
missed that c9bf07e493395a1bca7a975fa59bf227e593469c ("drivers/tty/amiserial.c:
add missing tty_unlock") just added a new caller of tty_unlock():

drivers/tty/amiserial.c: In function ‘set_serial_info’:
drivers/tty/amiserial.c:1077: error: too few arguments to function ‘tty_unlock’

Signed-off-by: Geert Uytterhoeven <geert@linux-m68k.org>
Cc: Alan Cox <alan@linux.intel.com>
Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>