Revert "mmc: tmio-mmc: Remove .set_pwr() callback from platform data"
This reverts commit f46a482d80c36b82a3dc6da3fa0fabb090304dac, which
causes a build failure:

drivers/mfd/asic3.c:724:2: error: unknown field 'set_pwr' specified in initializer