usb: typec/s2mf301: Guard water_wake_work worker properly
This fails to build for non Qcom arches because the struct member it uses
depends on CONFIG_ARCH_QCOM.

../drivers/usb/typec/slsi/s2mf301/s2mf301-usbpd.c:5343:32: error: no member named 'water_wake_work' in 'struct s2mf301_usbpd_data'
 5343 |         INIT_DELAYED_WORK(&pdic_data->water_wake_work,
      |                            ~~~~~~~~~  ^
../drivers/usb/typec/slsi/s2mf301/s2mf301-usbpd.c:5343:32: error: no member named 'water_wake_work' in 'struct s2mf301_usbpd_data'
 5343 |         INIT_DELAYED_WORK(&pdic_data->water_wake_work,
      |                            ~~~~~~~~~  ^
../drivers/usb/typec/slsi/s2mf301/s2mf301-usbpd.c:5343:32: error: no member named 'water_wake_work' in 'struct s2mf301_usbpd_data'
 5343 |         INIT_DELAYED_WORK(&pdic_data->water_wake_work,
      |                            ~~~~~~~~~  ^
../drivers/usb/typec/slsi/s2mf301/s2mf301-usbpd.c:5343:32: error: no member named 'water_wake_work' in 'struct s2mf301_usbpd_data'
 5343 |         INIT_DELAYED_WORK(&pdic_data->water_wake_work,
      |                            ~~~~~~~~~  ^
../drivers/usb/typec/slsi/s2mf301/s2mf301-usbpd.c:5344:3: error: use of undeclared identifier 's2mf301_usbpd_water_wake_work'; did you mean 's2mf301_usbpd_probe_reset_work'?
 5344 |                 s2mf301_usbpd_water_wake_work);
      |                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                 s2mf301_usbpd_probe_reset_work
../include/linux/workqueue.h:279:29: note: expanded from macro 'INIT_DELAYED_WORK'
  279 |         __INIT_DELAYED_WORK(_work, _func, 0)
      |                                    ^~~~~
../include/linux/workqueue.h:264:30: note: expanded from macro '__INIT_DELAYED_WORK'
  264 |                 INIT_WORK(&(_work)->work, (_func));                     \
      |                                            ^~~~~
../include/linux/workqueue.h:257:24: note: expanded from macro 'INIT_WORK'
  257 |         __INIT_WORK((_work), (_func), 0)
      |                               ^~~~~
../include/linux/workqueue.h:252:20: note: expanded from macro '__INIT_WORK'
  252 |                 (_work)->func = (_func);                                \
      |                                  ^~~~~
../drivers/usb/typec/slsi/s2mf301/s2mf301-usbpd.c:4664:13: note: 's2mf301_usbpd_probe_reset_work' declared here
 4664 | static void s2mf301_usbpd_probe_reset_work(struct work_struct *work)
      |             ^
../drivers/usb/typec/slsi/s2mf301/s2mf301-usbpd.c:5343:32: error: no member named 'water_wake_work' in 'struct s2mf301_usbpd_data'
 5343 |         INIT_DELAYED_WORK(&pdic_data->water_wake_work,
      |                            ~~~~~~~~~  ^
6 errors generated.

Signed-off-by: Flopster101 <nahuelgomez329@gmail.com>