sensorhub: sensor: adapt older drivers to new parse_dt API
It now requires an id parameter, even if it's unused.

Example error:

../drivers/sensorhub/sensor/physical_sensor/gyroscope/gyroscope_icm42605m.c:36:14: error: incompatible function pointer types initializing 'void (*)(struct device *, int)' with an expression of type 'void (struct device *)' [-Wincompatible-function-pointer-types]
   36 |         .parse_dt = parse_dt_gyroscope_icm24605m,
      |                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
make[3]: *** [../scripts/Makefile.build:273: drivers/sensorhub/sensor/physical_sensor/gyroscope/gyroscope_icm42605m.o] Error 1
  CC [M]  drivers/input/sec_input_legacy/legacy_sec_tclm_v2.o
../drivers/sensorhub/sensor/physical_sensor/accelerometer/accelerometer_icm42632m.c:37:14: error: incompatible function pointer types initializing 'void (*)(struct device *, int)' with an expression of type 'void (struct device *)' [-Wincompatible-function-pointer-types]
   37 |         .parse_dt = parse_dt_accelerometer_icm42632m,
      |                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.

Signed-off-by: Flopster101 <nahuelgomez329@gmail.com>