drivers: usb: hub: Remove unused variable after 5.10.241 merge
../drivers/usb/core/hub.c:5787:6: error: unused variable 'err' [-Werror,-Wunused-variable]
 5787 |         int err;
      |             ^~~
1 error generated.

Signed-off-by: Flopster101 <nahuelgomez329@gmail.com>