linux-next: fix x86 tree build failure
Today's linux-next build (powerpc allyesconfig) failed like this:

drivers/char/agp/uninorth-agp.c:541: error: unknown field 'agp_destroy_paged' specified in initializer

Caused by commit 2bb8381bc27b87b244e4715197967867cecc1081
("agp: enable optimized agp_alloc_pages methods").  A simple typo ...

Signed-off-by: Stephen Rothwell <sfr@canb.auug.org.au>
Signed-off-by: Ingo Molnar <mingo@elte.hu>